### ISSUE TITLE
Fails to load in ComfyUI

### ISSUE THREAD

**Issue by aurel-g** [xlinx/ComfyUI-decadetw-spout-syphon-im-vj#4]
Python 3.11 on Linux, with the current version of ComfyUI

```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-decadetw-spout-syphon-im-vj/__init__.py", line 21, in <module>
    from .im_sd_vj import *
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-decadetw-spout-syphon-im-vj/im_sd_vj.py", line 15, in <module>
    import SpoutGL
ModuleNotFoundError: No module named 'SpoutGL'



Cannot import /mnt/comfyui/app/custom_nodes/ComfyUI-decadetw-spout-syphon-im-vj module for custom nodes: No module named 'SpoutGL'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/ComfyUI-decadetw-spout-syphon-im-vj

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

**Comment by aurel-g** [comment]
My bad, I didn't install Spout (and I'm on Linux btw)
